language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly


test:
  override:
    - php vendor/codeception/codeception/codecept run

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer install --prefer-dist --no-interaction

